LANGUAGES = {
    "PT": {
        "loading":        "A carregar dados...",
        "no_atc":         "Sem ATC online",
        "no_position":    "Sem ATC com posição disponível",
        "refresh":        "Atualizar",
        "settings":       "Definições",
        "main":           "Principal",
        "language":       "Língua",
        "alert_distance": "Distância de alerta (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC próximo",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Notificações no telemóvel",
        "ntfy_topic":     "Tópico ntfy",
        "theme":          "Tema",
        "theme_light":    "Claro",
        "theme_dark":     "Escuro",
        "theme_system":   "Sistema",
    },
    "EN": {
        "loading":        "Loading data...",
        "no_atc":         "No ATC online",
        "no_position":    "No ATC with position available",
        "refresh":        "Refresh",
        "settings":       "Settings",
        "main":           "Main",
        "language":       "Language",
        "alert_distance": "Alert distance (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC nearby",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Phone notifications",
        "ntfy_topic":     "ntfy topic",
        "theme":          "Theme",
        "theme_light":    "Light",
        "theme_dark":     "Dark",
        "theme_system":   "System",
    },
    "ES": {
        "loading":        "Cargando datos...",
        "no_atc":         "Sin ATC en línea",
        "no_position":    "Sin ATC con posición disponible",
        "refresh":        "Actualizar",
        "settings":       "Ajustes",
        "main":           "Principal",
        "language":       "Idioma",
        "alert_distance": "Distancia de alerta (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC cercano",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Notificaciones en el móvil",
        "ntfy_topic":     "Tema ntfy",
        "theme":          "Tema",
        "theme_light":    "Claro",
        "theme_dark":     "Oscuro",
        "theme_system":   "Sistema",
    },
    "FR": {
        "loading":        "Chargement...",
        "no_atc":         "Aucun ATC en ligne",
        "no_position":    "Aucun ATC avec position disponible",
        "refresh":        "Actualiser",
        "settings":       "Paramètres",
        "main":           "Principal",
        "language":       "Langue",
        "alert_distance": "Distance d'alerte (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC à proximité",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Notifications sur téléphone",
        "ntfy_topic":     "Sujet ntfy",
        "theme":          "Thème",
        "theme_light":    "Clair",
        "theme_dark":     "Sombre",
        "theme_system":   "Système",
    },
    "DE": {
        "loading":        "Daten werden geladen...",
        "no_atc":         "Kein ATC online",
        "no_position":    "Kein ATC mit Position verfügbar",
        "refresh":        "Aktualisieren",
        "settings":       "Einstellungen",
        "main":           "Haupt",
        "language":       "Sprache",
        "alert_distance": "Alarmabstand (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC in der Nähe",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Handybenachrichtigungen",
        "ntfy_topic":     "ntfy-Thema",
        "theme":          "Design",
        "theme_light":    "Hell",
        "theme_dark":     "Dunkel",
        "theme_system":   "System",
    },
    "IT": {
        "loading":        "Caricamento dati...",
        "no_atc":         "Nessun ATC online",
        "no_position":    "Nessun ATC con posizione disponibile",
        "refresh":        "Aggiorna",
        "settings":       "Impostazioni",
        "main":           "Principale",
        "language":       "Lingua",
        "alert_distance": "Distanza di allerta (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC nelle vicinanze",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Notifiche sul telefono",
        "ntfy_topic":     "Argomento ntfy",
        "theme":          "Tema",
        "theme_light":    "Chiaro",
        "theme_dark":     "Scuro",
        "theme_system":   "Sistema",
    },
    "NL": {
        "loading":        "Gegevens laden...",
        "no_atc":         "Geen ATC online",
        "no_position":    "Geen ATC met positie beschikbaar",
        "refresh":        "Vernieuwen",
        "settings":       "Instellingen",
        "main":           "Hoofd",
        "language":       "Taal",
        "alert_distance": "Waarschuwingsafstand (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC in de buurt",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Telefonmeldingen",
        "ntfy_topic":     "ntfy-onderwerp",
        "theme":          "Thema",
        "theme_light":    "Licht",
        "theme_dark":     "Donker",
        "theme_system":   "Systeem",
    },
    "RU": {
        "loading":        "Загрузка данных...",
        "no_atc":         "Нет ATC онлайн",
        "no_position":    "Нет ATC с доступной позицией",
        "refresh":        "Обновить",
        "settings":       "Настройки",
        "main":           "Главная",
        "language":       "Язык",
        "alert_distance": "Дистанция оповещения (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC рядом",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Уведомления на телефон",
        "ntfy_topic":     "Тема ntfy",
        "theme":          "Тема",
        "theme_light":    "Светлый",
        "theme_dark":     "Тёмный",
        "theme_system":   "Система",
    },
    "TR": {
        "loading":        "Veriler yükleniyor...",
        "no_atc":         "Çevrimiçi ATC yok",
        "no_position":    "Konumu olan ATC yok",
        "refresh":        "Yenile",
        "settings":       "Ayarlar",
        "main":           "Ana",
        "language":       "Dil",
        "alert_distance": "Uyarı mesafesi (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC yakında",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "Telefon bildirimleri",
        "ntfy_topic":     "ntfy konusu",
        "theme":          "Tema",
        "theme_light":    "Açık",
        "theme_dark":     "Koyu",
        "theme_system":   "Sistem",
    },
    "ZH": {
        "loading":        "正在加载数据...",
        "no_atc":         "无ATC在线",
        "no_position":    "无可用位置的ATC",
        "refresh":        "刷新",
        "settings":       "设置",
        "main":           "主页",
        "language":       "语言",
        "alert_distance": "警报距离 (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "附近有ATC",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "手机通知",
        "ntfy_topic":     "ntfy主题",
        "theme":          "主题",
        "theme_light":    "浅色",
        "theme_dark":     "深色",
        "theme_system":   "系统",
    },
    "JA": {
        "loading":        "データを読み込み中...",
        "no_atc":         "オンラインのATCなし",
        "no_position":    "位置情報のあるATCなし",
        "refresh":        "更新",
        "settings":       "設定",
        "main":           "メイン",
        "language":       "言語",
        "alert_distance": "警告距離 (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATCが近くにいます",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "電話通知",
        "ntfy_topic":     "ntfyトピック",
        "theme":          "テーマ",
        "theme_light":    "ライト",
        "theme_dark":     "ダーク",
        "theme_system":   "システム",
    },
    "KO": {
        "loading":        "데이터 로딩 중...",
        "no_atc":         "온라인 ATC 없음",
        "no_position":    "위치 정보가 있는 ATC 없음",
        "refresh":        "새로고침",
        "settings":       "설정",
        "main":           "메인",
        "language":       "언어",
        "alert_distance": "경고 거리 (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC 근처",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "전화 알림",
        "ntfy_topic":     "ntfy 주제",
        "theme":          "테마",
        "theme_light":    "밝음",
        "theme_dark":     "어두움",
        "theme_system":   "시스템",
    },
    "HI": {
        "loading":        "डेटा लोड हो रहा है...",
        "no_atc":         "कोई ATC ऑनलाइन नहीं",
        "no_position":    "स्थिति वाला कोई ATC उपलब्ध नहीं",
        "refresh":        "ताज़ा करें",
        "settings":       "सेटिंग्स",
        "main":           "मुख्य",
        "language":       "भाषा",
        "alert_distance": "अलर्ट दूरी (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC पास में है",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "फोन सूचनाएं",
        "ntfy_topic":     "ntfy विषय",
        "theme":          "थीम",
        "theme_light":    "हल्का",
        "theme_dark":     "गहरा",
        "theme_system":   "सिस्टम",
    },
    "AR": {
        "loading":        "جارٍ تحميل البيانات...",
        "no_atc":         "لا يوجد ATC متصل",
        "no_position":    "لا يوجد ATC بموقع متاح",
        "refresh":        "تحديث",
        "settings":       "الإعدادات",
        "main":           "الرئيسية",
        "language":       "اللغة",
        "alert_distance": "مسافة التنبيه (NM)",
        "alert_title":    "ATC Advisor",
        "alert_msg":      "ATC قريب",
        "auto_refresh":   "Auto-refresh",
        "ntfy_label":     "إشعارات الهاتف",
        "ntfy_topic":     "موضوع ntfy",
        "theme":          "المظهر",
        "theme_light":    "فاتح",
        "theme_dark":     "داكن",
        "theme_system":   "النظام",
    },
}
